### PR TITLE
Upgrade Go version to version 1.16

### PR DESCRIPTION
**Pull request by Tenzer**
This will allow cross compiling releases to be compatible with macOS arm64.
https://goreleaser.com/deprecations/#builds-for-darwinarm64

### CODE REVIEW

**Comment by winebarrel** [comment]
👀

**Comment by winebarrel** [comment]
Thank you 😃

**Comment by Tenzer** [comment]
You're welcome!

**Comment by Tenzer** [comment]
Looks like it worked, thanks a lot :)

**Pull request merged**
